name: Simple CD

on:
  workflow_run:
    workflows: ["Simple CI"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: CD Success
        run: echo "cd deu certo também patrão 👍"
